### ISSUE TITLE
Handling Revamp - Honton Version X

### ISSUE THREAD

**Issue by Senlar** [Senlar/ncrp_issues#3]
We continue to learn as we go here at New Chance and when it comes to handling that is no different. Our currently handling isn't exactly where we want it to be so we're launching a new handling project!

**### **Handling Revamp - Honton Version X****

_What do we hope to accomplish with this new handling version?_
There are a number of things that need to be addressed with this project and it is not small task! Our overall goal here is to make sure vehicle handling is semi-realistic and focuses on ROLEPLAY fun and enjoyment instead of arcade style racing sim. So here is the list of things this handling revamp will address!

- A true racing car class system with appropriate ranges of acceleration and top speed to be included in the class groupings.
- Ensuring 100% of the currently available GTA Vehicles are included in the file and available in the server! (Yes including all DLCS)
- Building a framework to allow for easier addition of addon vehicles at a later date
- Including a system where player feedback can more easily be reviewed and allowing for an easier process to making changes.

**### ROADMAP**

- [ ] Defining the class based limits for acceleration and top speed
- [ ] Dividing the GTA vehicles appropriately among the different class groups
- [ ] Dividing the GTA vehicles appropriately among the different class groups
- [ ] Complete S Class handling changes
- [ ] Complete A Class handling changes
- [ ] Complete B Class handling changes
- [ ] Complete C Class handling changes
- [ ] Complete D Class handling changes
- [ ] Complete Motorcycle handling changes

**Comment by Senlar** [comment]
Progress has been made.

**Comment by Senlar** [comment]
Updated project with additional steps of vehicles additions and repricing

**Comment by HontonX** [comment]
Current Update: 
Current car list has been thoroughly been tested to ensure the data that has been collected are accurate. 
After data collection, any notes to the acceleration, top speed. of all the vehicles have been applied and retested. 
At this moment another run through the vehicles is being done to ensure the changes made are quality and consistent without any bugs. Some vehicles requiring little adjustments and need more testing. However I expect to be completed soon.

**Comment by Senlar** [comment]
Honton is on revision 3 of the handling and just needs to do more testing to ensure things are uniform before we move on to the next step in the process.
